#!/bin/bash
export PATH="$HOME/bin:/usr/bin:/usr/sbin:/bin"
trap '' TSTP 18 20 24
# A wrapper to start application and auto view log
h="$HOME/vr"
m="$(dirname "$(readlink -f "$0")")"
scr="${m}/vrex"
slog="${h}/vrex.log"


	if [ ! -d "${h}" ]; then
	mkdir -p "${h}"
	fi

	>"${slog}"
	
	
"${scr}" "$@"
tail -f -n +1 "${slog}"| { sed /^[[:space:]][[:space:]][[:space:]][[:space:]][[:space:]]$/q; pkill -f "${slog}"; }

